### ISSUE TITLE
404 on chaosnetz.org/downloads

### ISSUE THREAD

**Issue by NoNamePro0** [cccc/homepage_chaosnetz#2]
Server ([chaosnetz.org](https://chaosnetz.org)) doesn't have Downloads for http://chaosnetz.org/pages/smartphones-fuer-fluechtlinge.html

**Comment by yanosz** [comment]
Danke für den Hinweis! Die Smartphone-Sammlung ist inzwischen eingestellt. Ich habe die Links entfernt.
